name: asmara_dine
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pusher_channels_flutter: ^2.5.0
  flutter_bloc: ^9.1.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/asmaraLogo.jpeg
    - assets/asmaraOuter.jpeg
    - assets/asmaraIndoor.jpg
    - assets/asmaraCartoon.jpeg
    - assets/asmara_logo.jpeg

